server:
  port: 8084

spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/tumo?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000

  #thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

    #devtools插件
  devtools:
    restart:
      enabled: true #是否支持热部署

    #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.tycoding.admin.entity
  configuration:
    map-underscore-to-camel-case: true

#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

# 打印sql
logging:
  level:
    cn.tycoding.admin.mapper: DEBUG

# 七牛云
qiniu:
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
  bucket_name: BUCKETNAME
  url: http://xxx/